version: '3.8'

services:
  app:
    image: trungtp129/blog:v1.0.0
    container_name: blog-app
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      NODE_ENV: production
      PORT: 8081
      API_PREFIX: api
      API_VERSION: v1
      DATABASE_URL: postgresql://postgres.chioroyfjmazqxpnouek:tptrung1292@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      JWT_SECRET: 26ffeaacd14609a3aa77d5fe55648648
      JWT_EXPIRES_IN: 7d
      THROTTLE_TTL: 60000
      THROTTLE_LIMIT: 100
      ADMIN_EMAIL: admin@blog.com
      ADMIN_PASSWORD: Admin@123
      ADMIN_NAME: Admin
